ryosuke-hirai/HORMONE

- para/parameters_iotest
- src/io.F90
- src/iotest.f90
- src/mpi_domain.F90
- src/mpi_utils.F90
Add functionality for writing `spc` and `species` arrays with/without MPI
These arrays are now also part of `iotest`
> Mpi io species

- .github/workflows/test.yml
- src/gridset.f90
- src/sedov.f90
- Adjust sedov initial conditions to work with MPI - reduce the sum of cell volumes across MPI tasks
- Fix grid setup for MPI for cylindrical and spherical coordinates (use _global indices where required)
- Enable the sedov test in Github Actions
Changed MPI tests to use 2 tasks instead of 4 to avoid performance issues on GitHub runners
> Fix sedov blast problem for MPI

- src/mpi_domain.F90
In the existing MPI implementation, the grid is split between MPI tasks evenly along the longest axis. This is the optimal solution for 1D problems, and acceptable in 2D and 3D when the number of MPI tasks is small. However, for larger numbers of MPI tasks, this results in strips (2D) or slabs (3D) that have a large surface area relative to the enclosed volume.
The optimal solution is to divide the domain into volumes as close to squares/cubes as possible. In this new implementation, this is achieved by finding the prime factors of the number of available MPI tasks, and successively dividing the grid along the longest axis by these factors.
This implementation will use all available MPI tasks. For unusual choices for the number of MPI tasks, such as prime numbers, this can still result in …
> 3D MPI domain decomposition

- .gitignore
- para/parameters_iotest
- src/io.F90
- src/iotest.f90
- src/mpi_domain.F90
- src/mpi_utils.F90
- src/output.f90
- src/sinks.f90
This PR implements I/O with MPI for the sink array
- Created custom MPI type for sinks
- Each task stores a copy of all sinks
- Added to iotest
- Added the 'sequence' attribute to sink_prop type to ensure attributes always appear in the same order in memory. Note: this doesn't ensure it's contiguous in memory -- the custom MPI type handles any 'holes' the compiler might create
- Only write ascii sink output on master task. Note: not tested.
- Note: actual integration of sinks with MPI not implemented yet
> Implement MPI IO for sinks

- src/mpi_domain.F90
- src/mpi_utils.F90
- src/output.f90
- src/profiler.f90
Each MPI task keeps its own profiling clocks. Prior to output, they reduce their clocks, and the master task writes the ASCII output.
The average walltime for each category gives the most meaningful diagnostic, because it indicates where time is spent. Simply taking the max may not be useful, because a task that finishes a step quickly will record less time in that step, but more time in the subsequent step, meaning the times may add up to more than the total time.
An additional column `imbalance` is added, which measures the fraction `(max - min)/avg` of each clock. 0% indicates that every task recorded the same amount of time within that clock, and a non-zero value indicates load imbalance.
A clock `wtmpi` is added to time the MPI neighbour exchange subroutine.
This is an example …
> MPI-compatible profiling

- src/boundarycondition.f90
#23 adds logical switches to determine if a dimension is active.
This PR resolves a TODO in the boundary condition routine, which previously used the array indices to determine a dimension is active. It is not reliable in MPI because a given MPI task's subdomain may only be one cell wide.
> Boundary conditions: Use logical switches to determine if a dimension is active

- .github/workflows/test.yml
- para/parameters_orszagtang_xy
- para/parameters_orszagtang_xz
- para/parameters_orszagtang_yz
- para/parameters_sedov_default
- para/parameters_star_sph
- src/tests.f90
Fixes a bug caused by a debugging change being accidentally committed. This resulted in the L2 norm missing the denominator.
Enables the star_sph test with tolerance 2d-5.
Changes tolerance of other tests to account for denominator term:
- orszagtang: 4d-15
- sedov: 2d-14
> Fix L2 norm, enable star_sph test

- src/mpi_domain.F90
Previously, the `spc` array was exchanged by looping over each species. This resulted in a temporary array being created by the compiler because the elements were not contiguous in memory.
Using a dedicated subarray improves performance and eliminates the need for a temporary array to be explicitly created due to array slicing.
Other changes: Refactor the calculation of the number of times the exchange needs to occur into a function. This eliminates some duplicate code between the `_scalar` and `_spc` exchange subroutines.
> Dedicated MPI subarray for exchanging spc array

- src/io.F90
- src/iotest.f90
- src/mpi_domain.F90
- src/output.f90
- src/utils.f90
- work/Makefile
This PR implements parallel IO for the ascii output files created by `write_grid_dat` and `write_plt`. As part of this, we also parallelised the `gravpot1d` routine.
The subroutines function much the same as before, looping over the global indices, and only writing to the file if they "own" the current set of indices `i,j,k`
We've also simplified the wrapper `open_file_write` routine and added a separate `open_file_write_ascii`
> Parallel IO for ascii output files

- para/parameters_orszagtang_xy
- para/parameters_orszagtang_xz
- para/parameters_orszagtang_yz
- para/parameters_star_sph
- src/tests.f90
In the existing implementation of error normalisation, the normalisation factor depends on the test tolerance.
The error should be independent of the desired tolerance. One practical reason for this is so that a "correct" simulation can be run, the error determined, and then the tolerance set accordingly. If the error depends on the tolerance, then the test author would need to iterate to the correct tolerance.
In this new implementation, the normalisation factor is at minimum `epsilon(valorg)`. Furthermore, for vector values, the normalisation factor is the magnitude of the vector, not just the component in the given axis.
Test tolerances adjusted. Notably, `star_sph` now runs with a much tighter tolerance.
> Test normalisation

- src/star_init.f90
Fixes #45 
`fe56` is specified in the file `extras_star`, but is not present as a column in the MESA data `sun_profile.data`. As a side note, it is present as `co56_fe56` but this doesn't match the string so it is never used.
This results in the fe56 abundance being uninitialised in the `spc` array. Although unsafe, in gfortran this always seems to be fine, but not in the latest version of `ifx`.
This is fixed by setting `spc` and `spc_bg` to zero before applying the interpolated values from the MESA data.
> Fix divide by zero errors in test suite

- src/hormone.f90
- src/iotest.f90
- src/mpi_utils.F90
When `stop` is called with a non-zero exit code, MPI raises many multi-line errors - one per MPI task. For large numbers of MPI tasks, this results in a lot of noise that can obscure the actual error.
This PR adds the subroutine `mpi_stop` which calls `MPI_FINALIZE` before stopping with an exit code, resulting in a cleaner output. Importantly, the exit code is still preserved, which is necessary for the test suite.
Existing `stop` calls with a non-zero exit code have been replaced, but regular `stop`s have been left unchanged.
> Clean MPI exit

- src/io.F90
The `mpi_file_sync` call in `get_file_end` is extremely slow on the Lustre file system, and results in the file output time exceeding the actual computation time.
Switching to the alternate method (already implemented) results in a 2700x speedup in I/O when running with MPI on Lustre.
> Fix slow I/O with MPI

- src/utils.f90
This makes the masscoordinate function MPI safe.
The outer loop iterates over all radial cells `i = is_global, ie_global`. If the MPI task contains cells in that shell, it adds to `shellmass`. Otherwise, `shellmass` remains zero.
A call to `allreduce_mpi` sums up contributions to that shell from all MPI tasks. MPI tasks which do not contain that shell contribute zero. Then `shellmass` is added to the array `mc`.
> Make masscoordinate function MPI-safe

- para/extras_eruption
- para/parameters_base
- para/parameters_eruption
- src/checksetup.f90
- src/composition.f90
- src/eruption.f90
- src/initialcondition.f90
- src/input.f90
- src/modules.f90
- src/output.f90
- src/rsg.f90
- src/setup.f90
- src/star_init.f90
- src/stellarcollision.f90
- work/Makefile
- work/startfile
Some students are now working on HORMONE to reproduce results from Owocki+2019.
The code has evolved significantly since the publication, so a lot of work is needed to recreate the initial conditions to reproduce that work.
In the process, I have also added the following functionalities.
- `write_mc`: An option to output the mass coordinates for spherical coordinate simulations.
- `compswitch==1`: The spherical composition functionality was broken, but should now work.
> Add eruption subroutine to reproduce Owocki+2019

- src/checksetup.f90
- src/conserve.f90
- src/hormone.f90
- src/numflux.f90
- src/rungekutta.f90
The 9-wave method for magnetic field divergence cleaning should only be applied for multi-dimensional simulations. The damping in 1D could in fact be harmful.
Restrict the use of divergence cleaning to multi-D.
> Only apply divergence cleaning for multi-D

- src/star.f90
- work/Makefile
The star setup involves operations that easily lose precision, which can lead to different numerical values on different machines. These small differences can grow into larger errors, which we found to be the case for the polytrope case.
Simply changing the order of operations in the star setup routine reduces the loss of precision significantly.
Other changes:
- Add `-g` to debug flags in Makefile
> Reduce loss of precision

- src/mpi_domain.F90
- src/output.f90
Solves a race condition.
This makes the timestep loop for FMR non-blocking, but barriers need to be added back into the output routines to prevent tasks from writing at the same time
> remove mpi_barrier from is_my_domain

- src/gravity.f90
- src/gravity_hyperbolic.f90
This PR fixes 3 bugs affecting gravity + MPI
- Gravity relaxation is run for at least 2 iterations rather than 1. `grvpsi` is only non-zero after the first iteration, so this allows for better fault-finding when trying to isolate a problem between the hydro and gravity solvers
- Gravity MPI exchange is performed before every RK step
- Periodic boundary conditions in the phi direction fixed for MPI with more than 1 task
> Gravity bugfix

- src/checksetup.f90
- src/interpolation.f90
- src/mpi_domain.F90
- src/numflux.f90
- src/output.f90
- src/profiler.f90
- src/sn2022jli.f90
- src/timestep.f90
There was a typo in the `setup_mpi_exchange` routine for the size of the ghost cell array for `spc`.
Fixed this bug along with some other cosmetic changes to the code.
> Fix MPI bug in exchange spc

- src/mpi_utils.F90
- src/output.f90
- src/profiler.f90
- src/rungekutta.f90
- src/smear.f90
- src/star.f90
- src/utils.f90
Fixed the following small bugs
- `write_vertical_slice` was outputted in the wrong unit number.
- smearing for `spc` was MPI unsafe.
- `softened_pot` and `softened_acc` could crash when `r=hsoft=0d0`.
> Bug fixes and profiler for smearing

- src/allocations.f90
- src/gravity_hyperbolic.f90
- src/metric.f90
- src/mpi_domain.F90
- src/mpi_utils.F90
- src/output.f90
- src/smear.f90
- src/sn2022jli.f90
Smearing is a severe bottleneck for the simulation for MPI runs.
This is because there is a lot of global summations going on and therefore the whole subroutine is a serial run without even OpenMP parallelization.
This can be improved by doing two sweeps of smearing.
In the first sweep, all effective cells that are fully contained within an MPI rank can be smeared in the classical way with OpenMP parallelization. At this point, we record the cells that have been smeared already.
In the second sweep, we smear the cells that were not smeared previously. These effective cells should all span over multiple MPI ranks so should be done in serial with global reduction.
With this method, the only MPI communication that happens is for the cells that span over multiple MPI ranks. In practice, most …
> Optimize smearing

- src/gravity_hyperbolic.f90
- src/profiler.f90
- src/rungekutta.f90
- src/smear.f90
- src/tools.f90
In a previous pull request #76, I forgot to apply the same changes to the gravity smearing.
Here, I do the same optimization for gravity smearing and also introduced a new variable `dvol_block`. With this fix, we may not need to make `dvol` as a global variable any more.
> Optimize gravity smearing

- src/allocations.f90
- src/gridset.f90
- src/io.F90
- src/iotest.f90
- src/modules.f90
- src/mpi_domain.F90
- src/mpi_utils.F90
- src/readbin.f90
- src/setup.f90
- src/sinks.f90
For some reason, the MPI output is not working on OzStar.
When compared to a serial run, the MPI output is roughly half the size.
This is my branch attempting to fix this.
> MPI I/O error fix

- para/parameters_base
- para/parameters_sn2022jli
- src/ascii_output.f90
- src/gravity.f90
- src/modules.f90
- src/output.f90
- src/profiler.f90
- src/setup.f90
- src/smear.f90
- work/Makefile
In some machines like OzStar, the ascii output is extremely slow. Sometimes it is unbearably slow that it dominates the computing time.
In this PR, I convert the ascii output into a runtime option, and make a new mode that simply reads in binfile's and outputs pltfile's.
This new mode can be executed by 
```
$ make ascii
```
and then run `./ascii_output`.
At least on OzStar, this is most efficient when run without MPI.
Other small changes were introduced too.
- Made a new option to choose the name of the output directory. Defaulted to "data".
- Default choice for `output_ascii` set to `.false.` for the `sn2022jli` simtype, as it was unbearably slow on OzStar.
- Added extra profiler output for the MPI sweeps in `smear`
- Fixed a bug in `profiler_output1`
> Separate out ascii output

- src/ascii_output.f90
- src/smear.f90
- work/Makefile
- work/hokusai.sh
A quick bug fix to `angular_smear_global` to make it OpenMP safe.
Also enabled the `mpiifx` option for the Makefile as the HOKUSAI supercomputer only has Intel MPI and no modules for gfortran+OpenMPI.
> Quick bug fixes

- src/mpi_utils.F90
- src/smear.f90
This PR drastically changes `smear` so that it only does one or two MPI reduction calls.
I added two lists of effective cells to keep track of things.
`list_split`: List of effective cell IDs that are split over multiple MPI ranks.
`list_mydom(1,:)`: List of effective cell IDs that are partially covered by the domain. 
`list_mydom(2,:)`: ID within `list_split` if it is split over multiple MPI ranks. Set to 0 when it is not on `list_split`.
1. The first step sums up the conserved quantities (mass, momentum, energy, etc) over the effective cells. If only part of the effective cell is covered by the domain, the sum will only be a fraction of the total sum.
2. The second step reduces the summed up quantities over all MPI ranks.
3. The third step updates the local quantities by values averaged …
> Change smear to a 3-step process

- src/main/utils.f90
The `masscoordinate` routine was buggy for gfortran due to some parallelization error.
Now fixed.
> Debug masscoordinate for gfortran

- src/init/eruption.f90
Eva, Rafe and Stan spotted an error in the Ebind calculation inside the `eruption` module.
It turned out that the internal energy was computed as energy density, whereas it should be computed as specific energy.
Simple fix made it consistent with Owocki+2019.
> Debug Ebind calculation in eruption

- src/init/sn2022jli.f90
- src/main/output.f90
- src/main/source.f90
- src/post/ascii_output.f90
- work/Makefile
`evo_output` outputs the global quantities like total energy, total mass, total bound mass, etc.
This has not been updated since the sink particles were introduced.
I have now changed the definition of `bound_mass` to be the mass where the total energy is negative, including the gravitational potential to the sinks.
I also fixed a minor bug in the `sn2022jli` initial condition.
> Fix evo_output

- src/post/integrations.f90
- src/post/lightcurve.f90
Light curve calculations were extremely slow due to the way the ray tracing was done.
With this update, the ray tracing is shot from the observer side to the source, and terminated at sufficiently optically thick regions. This way, the ray does not need to go all the way through the computational region.
> Speed up light curve calculation

- src/main/utils.f90
This pull request refactors the `gravpot1d` subroutine in `src/main/utils.f90` to improve the computation of the gravitational potential.
**Reversed shell iteration order:** The loop now iterates over shells backwards (`ie_global` to `is_global`), removing the need for a nested for loop. This solves the issue of initialisation being **very** slow for large numbers of radial cells.
> Optimise radstar init

- work/data/plot.py
- work/scripts/horpy.f90
- work/scripts/horpy.sh
Adds a very primitive functionality for loading HORMONE binary files into python variables.
To use it, first do 
`$ sh horpy.sh`
in the `work/scripts` directory.
This generates a file called `horpy.so` in the `work` directory. Take that to wherever your python script is.
I placed an example python script `plot.py` in the `work/data` directory.
```
import horpy as hp
hp.readbin_python.setup_python('../')
```
`setup_python(<work directory>)` needs to be called first to allocate the variables inside HORMONE.
Then you can call the read routines by something like
```
hp.readbin_python.readgrid('gridfile.bin')
hp.readbin_python.readbin('bin00000000000s.dat')
```
This will read the files into the variables inside HORMONE.
To copy it to python variables, you need to do something like
``` …
```
> Python reader
